# Generated by Django 3.0.7 on 2020-06-19 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200619_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='itstaff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.ITStaff'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=3, null=True),
        ),
    ]
