# Generated by Django 3.0.7 on 2020-06-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200619_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date_added',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
