# Generated by Django 3.0.7 on 2020-06-27 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20200623_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itstaff',
            name='employee_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rating',
            name='employee_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rating',
            name='itstaff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ITStaff'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50),
        ),
    ]
